account:
  address: ":8000"
  rpc: ":1234"
  rpcURL: "localhost:1234"

db:
  testdb: "postgresql://aheadIV:oXnwUedJ47RI@ep-summer-tree-57217189-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"